apiVersion: apps/v1 
kind: Deployment
metadata:  
  name: kafka-broker 
spec:  
  replicas: 1
  selector:
    matchLabels:
      app: kafka-app 
  template:  
    metadata:  
      labels:  
        app: kafka-app
        id: "0" 
    spec:  
      hostname: kafka1
      containers:  
      - name: kafka-app  
        image: wurstmeister/kafka    
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "156.17.41.49"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zk-cluster:2181"
        - name: KAFKA_BROKER_ID
          value: "0"
        - name: KAFKA_LISTENERS 
          value: "PLAINTEXT://0.0.0.0:9092,ALICE://localhost:9093"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://156.17.41.49:9092,ALICE://localhost:9093"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "PLAINTEXT:PLAINTEXT,ALICE:PLAINTEXT"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "ALICE"
#        - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
#          value: "true"
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
