kind: Deployment
apiVersion: apps/v1
metadata:
  name: zk-deployment-1
spec:
  selector:
    matchLabels:
     app: zk1
  template:
    metadata:
      labels:
        app: zk1
    spec:
      hostname: zookeeper1
      containers:
      - name: zk1
        image: wurstmeister/zookeeper
        ports:
        - name: client
          containerPort: 2181
        - name: follower
          containerPort: 2188
        - name: leader
          containerPort: 3888
        env:
#        - name: ZOOKEEPER_ID
#          value: "1"
#        - name: ZOOKEEPER_SERVER_1
#          value: "zk1"
        - name: ALLOW_ANONYMOUS_LOGIN
          value: "yes"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "10.104.32.223"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "kafka-cluster:2181"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://10.104.32.223:2181"
        - name: KAFKA_LOG_RETENTION_MS
          value: "10000"
        - name: KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS
          value: "5000"


