version: '3'
services:
  kafka-1:
    image: landoop/fast-data-dev:2.5
    environment:
      - FORWARDLOGS=0
      - RUNTESTS=0
      - BROWSECONFIGS=0
      - RUNNING_SAMPLEDATA=0
      - KAFKA_ZOOKEEPER_CONNECT=10.104.32.222:2181
      - REST_PORT=0
      - SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=PLAINTEXT://10.104.32.222:9092
      - KAFKA_REST_BOOTSTRAP_SERVERS=PLAINTEXT://10.104.32.222:9092
      - CONNECT_BOOTSTRAP_SERVERS=PLAINTEXT://10.104.32.222:9092
      - CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL=http://10.104.32.222:8081
      - CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL=http://10.104.32.222:8081
      - KAFKA_REST_SCHEMA_REGISTRY_URL=http://10.104.32.222:8081
      - ADV_HOST=10.104.32.222
      - ADV_JMX_HOST=10.104.32.222
      - CONNECT_LISTENERS=http://0.0.0.0:8083
      - SCHEMA_REGISTRY_LISTENERS=http://0.0.0.0:8081
      - CONNECT_PORT=0
      - KAFKA_LOG_RETENTION_MS=10000
      - KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS=5000
      - BROKER_OPTS=-javaagent:/usr/local/jmx_exporter_agent.jar=9481:/usr/local/broker.yml
    network_mode: host
    volumes:
       - ./jmx_exporter.jar:/usr/local/jmx_exporter_agent.jar
       - ./broker.yml:/usr/local/broker.yml
#      - /var/run/docker.sock:/var/run/docker.sock



